// Diccionario base de palabras clave → categoría
// Las palabras personalizadas del usuario se guardan en Supabase (tabla diccionario_personal)
// y se fusionan en el parser en tiempo de ejecución.

export const DICCIONARIO_BASE = {
  // Transporte
  uber:       'transporte',
  taxi:       'transporte',
  cabify:     'transporte',
  beat:       'transporte',
  indrive:    'transporte',
  subte:      'transporte',
  colectivo:  'transporte',
  bondi:      'transporte',
  tren:       'transporte',
  tren:       'transporte',
  nafta:      'transporte',
  combustible:'transporte',
  peaje:      'transporte',
  autopista:  'transporte',
  estacionamiento: 'transporte',
  garaje:     'transporte',
  garage:     'transporte',
  mantenimiento: 'transporte',

  // Comida y supermercado
  super:       'comida',
  supermercado:'comida',
  almuerzo:    'comida',
  cena:        'comida',
  desayuno:    'comida',
  merienda:    'comida',
  delivery:    'comida',
  pedidos:     'comida',
  rappi:       'comida',
  café:        'comida',
  cafe:        'comida',
  cafeteria:   'comida',
  cafetería:   'comida',
  restaurant:  'comida',
  restaurante: 'comida',
  panaderia:   'comida',
  panadería:   'comida',
  kiosco:      'comida',
  mercado:     'comida',
  carniceria:  'comida',
  carnicería:  'comida',
  verduleria:  'comida',
  verdulería:  'comida',
  sushi:       'comida',
  pizza:       'comida',
  burger:      'comida',
  hamburguesa: 'comida',
  mcdonald:    'comida',
  wendy:       'comida',
  kfc:         'comida',
  starbucks:   'comida',
  wok:         'comida',
  empanadas:   'comida',
  medialunas:  'comida',
  heladeria:   'comida',
  heladería:   'comida',
  fiambreria:  'comida',
  fiambres:    'comida',
  dia:         'comida',
  coto:        'comida',
  carrefour:   'comida',
  jumbo:       'comida',
  disco:       'comida',
  vea:         'comida',

  // Vivienda
  alquiler:    'vivienda',
  expensas:    'vivienda',
  abl:         'vivienda',
  inmobiliaria:'vivienda',
  hipoteca:    'vivienda',
  cuota_casa:  'vivienda',

  // Servicios
  luz:         'servicios',
  gas:         'servicios',
  agua:        'servicios',
  internet:    'servicios',
  wifi:        'servicios',
  celular:     'servicios',
  telefono:    'servicios',
  teléfono:    'servicios',
  cable:       'servicios',
  telefonía:   'servicios',
  telefonia:   'servicios',
  claro:       'servicios',
  personal:    'servicios',
  movistar:    'servicios',
  tuenti:      'servicios',

  // Entretenimiento / salidas
  netflix:     'entretenimiento',
  spotify:     'entretenimiento',
  disney:      'entretenimiento',
  hbo:         'entretenimiento',
  prime:       'entretenimiento',
  apple:       'entretenimiento',
  cine:        'entretenimiento',
  teatro:      'entretenimiento',
  salida:      'entretenimiento',
  salidas:     'entretenimiento',
  bar:         'entretenimiento',
  boliche:     'entretenimiento',
  recital:     'entretenimiento',
  show:        'entretenimiento',
  juego:       'entretenimiento',
  steam:       'entretenimiento',
  play:        'entretenimiento',
  concierto:   'entretenimiento',
  entrada:     'entretenimiento',
  entradas:    'entretenimiento',
  evento:      'entretenimiento',

  // Salud
  farmacia:    'salud',
  farmalink:   'salud',
  farmacity:   'salud',
  medico:      'salud',
  médico:      'salud',
  doctor:      'salud',
  dentista:    'salud',
  psicólogo:   'salud',
  psicologo:   'salud',
  psicóloga:   'salud',
  psicologa:   'salud',
  remedio:     'salud',
  remedios:    'salud',
  medicamento: 'salud',
  clinica:     'salud',
  clínica:     'salud',
  hospital:    'salud',
  obra_social: 'salud',
  consulta:    'salud',

  // Ropa / indumentaria
  ropa:        'ropa',
  zapatillas:  'ropa',
  zapatos:     'ropa',
  indumentaria:'ropa',
  camiseta:    'ropa',
  pantalon:    'ropa',
  pantalón:    'ropa',
  vestido:     'ropa',
  remera:      'ropa',
  campera:     'ropa',
  buzo:        'ropa',
  medias:      'ropa',
  zara:        'ropa',
  hm:          'ropa',
  adidas:      'ropa',
  nike:        'ropa',
  puma:        'ropa',

  // Educación
  facultad:    'educacion',
  universidad: 'educacion',
  colegio:     'educacion',
  curso:       'educacion',
  libro:       'educacion',
  libros:      'educacion',
  fotocopias:  'educacion',
  fotocopia:   'educacion',
  arancel:     'educacion',
  cuota_colegio: 'educacion',
  udemy:       'educacion',
  educacion:   'educacion',
  educación:   'educacion',

  // Deporte
  gym:         'deporte',
  gimnasio:    'deporte',
  pilates:     'deporte',
  yoga:        'deporte',
  crossfit:    'deporte',
  natacion:    'deporte',
  natación:    'deporte',
  running:     'deporte',
  bici:        'deporte',
  deporte:     'deporte',

  // Compras generales
  mercadolibre:'compras',
  meli:        'compras',
  mercadolibre: 'compras',
  amazon:      'compras',
  ebay:        'compras',
  tienda:      'compras',
  ferreteria:  'compras',
  ferretería:  'compras',
  libreria:    'compras',
  librería:    'compras',
  bazar:       'compras',

  // Cuidado personal
  perfumeria:  'cuidado',
  perfumería:  'cuidado',
  peluqueria:  'cuidado',
  peluquería:  'cuidado',
  barberia:    'cuidado',
  barbería:    'cuidado',
  manicura:    'cuidado',
  depilacion:  'cuidado',
  depilación:  'cuidado',

  // Ingreso
  sueldo:      'ingreso',
  salario:     'ingreso',
  honorarios:  'ingreso',
  freelance:   'ingreso',
  venta:       'ingreso',
  ventas:      'ingreso',
  cobré:       'ingreso',
  cobranza:    'ingreso',
  bono:        'ingreso',
  aguinaldo:   'ingreso',
  quincena:    'ingreso',

  // Ahorro / Inversión
  ahorro:      'ahorro',
  ahorré:      'ahorro',
  inversion:   'ahorro',
  inversión:   'ahorro',
  plazo_fijo:  'ahorro',
  plazofijo:   'ahorro',
  fci:         'ahorro',
  dolar:       'ahorro',
  dólar:       'ahorro',
  cripto:      'ahorro',
  bitcoin:     'ahorro',
  cedear:      'ahorro',
  accion:      'ahorro',
  acción:      'ahorro',
  broker:      'ahorro',
  billetera:   'ahorro',
  mercadopago: 'ahorro',
}

// Palabras que indican tipo de movimiento
export const PALABRAS_TIPO = {
  gasto: [
    'gasté', 'gaste', 'compré', 'compre', 'pagué', 'pague',
    'salió', 'salio', 'costó', 'costo', 'desembolsé', 'puse',
    'me cobró', 'me cobraron', 'fui al', 'fui a',
    'me salió', 'me salio', 'me costó', 'me costo',
    'cargué', 'cargue', 'abonamos', 'aboné', 'abone',
  ],
  ingreso: [
    'cobré', 'cobre', 'me pagaron', 'recibí', 'recibi',
    'ingresó', 'me ingresó', 'gané', 'gane', 'entró', 'entro',
    'me transfirieron', 'me depositaron', 'me acreditaron',
    'me cayó el sueldo', 'me cayeron', 'me llegó',
  ],
  ahorro: [
    'ahorré', 'ahorre', 'guardé', 'guarde', 'invertí', 'inverti',
    'puse en', 'deposité', 'deposite', 'mandé al', 'mande al',
    'transferí a', 'transfiero a', 'moví a', 'movi a',
  ],
}

// Palabras de consulta (no registran movimiento)
export const PALABRAS_CONSULTA = [
  'cuánto gasté', 'cuanto gaste', 'cuánto gaste',
  'cómo voy', 'como voy', 'como estoy', 'cómo estoy',
  'resumen', 'balance', 'cuánto llevo', 'cuanto llevo',
  'qué gasté', 'que gaste', 'en qué gasté', 'en que gaste',
]
